# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Stash previous state
      - name: Stash Previous State
        run: git stash

      # Pull new changes

      - name: Pull new changes with git
        run: git pull origin master
        working-directory: C:\inetpub\wwwroot\mande


      # Run any new migrations

      - name: Run any migrations
        run: .\yii migrate --interactive=0
        working-directory: C:\inetpub\wwwroot\mande

      # Runs update /  install dependancies
      - name: Install dependancies via composer
        run: |
           echo Installing dependancies
            composer install 
            working-directory: C:\inetpub\wwwroot\mande
